[package]
name = "slimqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
nom = "7.1"

[dev-dependencies.tokio]
version = "1"
features = ["full"]